// This file was autogenerated by closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../js/Action.js', ['tm.Action'], []);
goog.addDependency('../../../js/BrainRegistry.js', ['tm.BrainRegistry'], ['tm.brains.Bastard', 'tm.brains.Farming', 'tm.brains.Greedy', 'tm.brains.Neural', 'tm.brains.Random', 'tm.brains.Selfish', 'tm.brains.Smart']);
goog.addDependency('../../../js/BrainSelector.js', ['tm.BrainSelector'], ['goog.dom', 'goog.dom.forms', 'goog.events', 'tm.BrainRegistry', 'tm.Teams', 'tm.World', 'tm.WorldGenerator']);
goog.addDependency('../../../js/Perception.js', ['tm.Perception'], ['tm.Tiles', 'tm.World']);
goog.addDependency('../../../js/Plant.js', ['tm.Plant'], []);
goog.addDependency('../../../js/Renderer.js', ['tm.Renderer'], ['tm.Tiles', 'tm.World']);
goog.addDependency('../../../js/Simulator.js', ['tm.Simulator'], ['tm.Plant', 'tm.Tiles', 'tm.Weed']);
goog.addDependency('../../../js/Start.js', ['tm.start'], ['goog.dom', 'tm.BrainSelector', 'tm.Renderer', 'tm.Simulator', 'tm.TeamUI', 'tm.Teams', 'tm.Termite', 'tm.World', 'tm.WorldGenerator']);
goog.addDependency('../../../js/TeamUI.js', ['tm.TeamUI'], ['goog.dom', 'tm.BrainSelector']);
goog.addDependency('../../../js/Teams.js', ['tm.Teams'], ['tm.brains.Random']);
goog.addDependency('../../../js/Termite.js', ['tm.Termite'], ['tm.Action', 'tm.Perception', 'tm.Teams', 'tm.Tiles']);
goog.addDependency('../../../js/Tiles.js', ['tm.Tiles'], []);
goog.addDependency('../../../js/Weed.js', ['tm.Weed'], []);
goog.addDependency('../../../js/World.js', ['tm.World'], ['tm.Termite']);
goog.addDependency('../../../js/WorldGenerator.js', ['tm.WorldGenerator'], ['tm.Tiles', 'tm.World']);
goog.addDependency('../../../js/brains/Bastard.js', ['tm.brains.Bastard'], ['tm.Action', 'tm.Tiles']);
goog.addDependency('../../../js/brains/Farming.js', ['tm.brains.Farming'], []);
goog.addDependency('../../../js/brains/Greedy.js', ['tm.brains.Greedy'], ['tm.Action', 'tm.Tiles']);
goog.addDependency('../../../js/brains/Neural.js', ['tm.brains.Neural'], ['tm.Plant']);
goog.addDependency('../../../js/brains/Random.js', ['tm.brains.Random'], []);
goog.addDependency('../../../js/brains/Selfish.js', ['tm.brains.Selfish'], []);
goog.addDependency('../../../js/brains/Smart.js', ['tm.brains.Smart'], ['tm.Action', 'tm.Tiles']);
goog.addDependency('../../../js/tm.js', ['tm'], []);
