// This file was autogenerated by closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../js/Action.js', ['tm.Action'], []);
goog.addDependency('../../../js/BrainRegistry.js', ['tm.BrainRegistry'], ['tm.brain.RandomBrain', 'tm.brain.SelfishBrain']);
goog.addDependency('../../../js/Perception.js', ['tm.Perception', 'tm.Tiles'], []);
goog.addDependency('../../../js/Plant.js', ['tm.Plant'], []);
goog.addDependency('../../../js/Renderer.js', ['tm.Renderer'], ['tm.Tiles', 'tm.World']);
goog.addDependency('../../../js/Simulator.js', ['tm.Simulator'], ['tm.Plant', 'tm.Tiles', 'tm.Weed']);
goog.addDependency('../../../js/Start.js', ['tm.start'], ['goog.dom', 'tm.Renderer', 'tm.Simulator', 'tm.Termite', 'tm.World', 'tm.WorldGenerator']);
goog.addDependency('../../../js/Termite.js', ['tm.Termite'], ['tm.Action', 'tm.Perception', 'tm.Tiles', 'tm.brains.RandomBrain']);
goog.addDependency('../../../js/Tiles.js', ['tm.Tiles'], []);
goog.addDependency('../../../js/Weed.js', ['tm.Weed'], []);
goog.addDependency('../../../js/World.js', ['tm.World'], ['tm.Termite']);
goog.addDependency('../../../js/WorldGenerator.js', ['tm.WorldGenerator'], ['tm.Tiles', 'tm.World']);
goog.addDependency('../../../js/brains/RandomBrain.js', ['tm.brains.RandomBrain'], []);
goog.addDependency('../../../js/brains/SelfishBrain.js', ['tm.brains.SelfishBrain'], []);
goog.addDependency('../../../js/tm.js', ['tm'], []);
