// This file was autogenerated by closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../js/Action.js', ['tm.Action'], []);
goog.addDependency('../../../js/BrainRegistry.js', ['tm.BrainRegistry'], ['tm.brains.Bastard', 'tm.brains.FarmingBrain', 'tm.brains.GreedyBrain', 'tm.brains.RandomBrain', 'tm.brains.SelfishBrain']);
goog.addDependency('../../../js/BrainSelector.js', ['tm.BrainSelector'], ['goog.dom', 'goog.dom.forms', 'goog.events', 'tm.BrainRegistry', 'tm.Teams', 'tm.World', 'tm.WorldGenerator']);
goog.addDependency('../../../js/Perception.js', ['tm.Perception'], ['tm.Tiles']);
goog.addDependency('../../../js/Plant.js', ['tm.Plant'], []);
goog.addDependency('../../../js/Renderer.js', ['tm.Renderer'], ['tm.Tiles', 'tm.World']);
goog.addDependency('../../../js/Simulator.js', ['tm.Simulator'], ['tm.Plant', 'tm.Tiles', 'tm.Weed']);
goog.addDependency('../../../js/Start.js', ['tm.start'], ['goog.dom', 'tm.BrainSelector', 'tm.Renderer', 'tm.Simulator', 'tm.TeamUI', 'tm.Teams', 'tm.Termite', 'tm.World', 'tm.WorldGenerator']);
goog.addDependency('../../../js/TeamUI.js', ['tm.TeamUI'], ['goog.dom', 'tm.BrainSelector']);
goog.addDependency('../../../js/Teams.js', ['tm.Teams'], ['tm.brains.RandomBrain']);
goog.addDependency('../../../js/Termite.js', ['tm.Termite'], ['tm.Action', 'tm.Perception', 'tm.Teams', 'tm.Tiles', 'tm.brains.RandomBrain']);
goog.addDependency('../../../js/Tiles.js', ['tm.Tiles'], []);
goog.addDependency('../../../js/Weed.js', ['tm.Weed'], []);
goog.addDependency('../../../js/World.js', ['tm.World'], ['tm.Termite']);
goog.addDependency('../../../js/WorldGenerator.js', ['tm.WorldGenerator'], ['tm.Tiles', 'tm.World']);
goog.addDependency('../../../js/brains/Bastard.js', ['tm.brains.Bastard'], ['tm.Action', 'tm.Tiles']);
goog.addDependency('../../../js/brains/FarmingBrain.js', ['tm.brains.FarmingBrain'], []);
goog.addDependency('../../../js/brains/GreedyBrain.js', ['tm.brains.GreedyBrain'], ['tm.Action', 'tm.Tiles']);
goog.addDependency('../../../js/brains/RandomBrain.js', ['tm.brains.RandomBrain'], []);
goog.addDependency('../../../js/brains/SelfishBrain.js', ['tm.brains.SelfishBrain'], []);
goog.addDependency('../../../js/tm.js', ['tm'], []);
